#!/bin/sh

[ -z $1 ] && exit 1 
n=1
# lz=$(echo "$(cat $1 | wc -l) / 10 + 1" | bc)
echo "l($(cat $1 | wc -l)+1) / l(10)" | bc -l | awk '!$0{print;next}{printf "%s\t%d\n",$0,($0%int($0))?int($0)+(($0>0)?1:0):$0}' | awk '{print $2}'
printf "%0${lz}d"

while IFS="" read -r p || [ -n "$p" ]
do
	lzn=$(printf "%0${lz}d" "$n")
	echo $lzn
	echo $p
	yt-dlp --no-part --restrict-filenames --referer "https://aniqit.com/" -o "$lzn.%(ext)s" -P "$(pwd)" "$p"
	n=$(expr $n + 1)
done < $1
