#!/bin/sh
# bluetooth script

TERM="st"

sel=$(echo "on\noff\nterm\nback\nexit" | rofi -dmenu -p "bluetooth")

case $sel in
	"on")
		bluetoothctl power on
		xset -dpms
		;;
	"off")
		bluetoothctl power off
		xset +dpms
		;;
	"term")
		$TERM "bluetoothctl"
	 	;;
	"back")
		exit 1
	 	;;
esac

exit 0
