#!/usr/bin/bash
# bluetooth script

TERM="scroll st"

choices=(
"on"
"off"
"term"
"back"
"exit"
)

sel=$(printf '%s\n' "${choices[@]}" | rofi -dmenu -p "bluetooth: ")

case $sel in
	"on")
		bluetoothctl power on
		;;
	"off")
		bluetoothctl power off
		;;
	"term")
		$TERM "bluetoothctl"
	 	;;
	"back")
		exit 1
	 	;;
esac

exit 0
