#!/etc/bin/bash

choices=(
"dota"
"nocturne"
)

sel=$(printf '%s\n' "${choices[@]}" | rofi -dmenu -p "game: ")

case $sel in
	"dota")
		steam "steam://rungameid/570" & exit 0
		;;
	"nocturne")
		pcsx2 "/home/ns/D/_games/_emulators/PCSX2/_games/Nocturne/SMT III - Nocturne Maniax Chronicle Edition [Eng-T Ver.1.1.3].iso"
		;;
esac

