#!/bin/sh

choices="
power off\nreboot\nsleep\nclose dwm\nexit
"

while true; do
	sel=$(echo $choices | rofi -dmenu -p "taskbar: ")
	
	case $sel in
		"power off")
			loginctl poweroff
			exit 0
			;;
		"reboot")
			loginctl reboot
			exit 0
			;;
		"sleep")
			loginctl suspend
			exit 0
		 	;;
		"close dwm")
			killall dwm
			exit 0
		 	;;
		"exit")
			exit 0
		 	;;
	esac

	[ -z $sel ] && exit 0
done

