#!/bin/sh

choices="
power off\nreboot\nsleep\nclose dwm\nexit
"

while true; do
	sel=$(echo $choices | rofi -dmenu -p "taskbar: ")
	
	case $sel in
		"power off")
			systemctl poweroff
			exit 0
			;;
		"reboot")
			systemctl reboot
			exit 0
			;;
		"sleep")
			systemctl suspend
			exit 0
		 	;;
		"close hyprland")
			hyprctl kill
			exit 0
		 	;;
		"exit")
			exit 0
		 	;;
	esac

	[ -z $sel ] && exit 0
done

