#!/bin/sh
#taskbar script

TERM="st"
tear=$(xrandr --prop | grep TearFree | grep -E '(on|off)' | awk '{print $2}')
tearn=$( [ $tear = "on" ] && echo off || echo on)
bt=$(bluetoothctl show | grep Powered | awk '{print $2}')
btn=$( [ $bt = "yes" ] && echo no || echo yes)
btc=$( [ $btn = "yes" ] && echo on || echo off)

choices="
htop\ncalcurse\npavucontrol\nbluetooth $btc\ntearfree $tearn\nkeymap-fix\nexit
"

while true; do
	sel=$(echo $choices | rofi -dmenu -p "taskbar: ")
	
	case $sel in
		"htop")
			$TERM "htop"
			exit 0
			;;
		"calcurse")
			$TERM "calcurse"
			exit 0
			;;
		"pavucontrol")
			pavucontrol & exit 0
		 	;;
		"bluetooth $btc")
			bluetoothctl power $btc
			[ $btc = "on" ] && xset -dpms || xset +dpms
			exit 0
		 	;;
		"tearfree $tearn")
			xrandr --output HDMI-A-0 --set TearFree $tearn
			exit 0
			;;		
		"keymap-fix")
			setxkbmap -layout us,ru -option grp:alt_shift_toggle
			exit 0
			;;
		"exit")
			exit 0
		 	;;
	esac

	[ -z $sel ] && exit 0
done
