#!/usr/bin/bash
#taskbar script

TERM="scroll st"

choices=(
"htop"
"calcurse"
"pavucontrol"
"bluetooth"
"exit"
)

sel=$(printf '%s\n' "${choices[@]}" | rofi -dmenu -p "taskbar: ")

#echo $sel

case $sel in
	"htop")
		$TERM "htop"
		;;
	"calcurse")
		$TERM "calcurse"
		;;
	"pavucontrol")
		pavucontrol & exit 0
	 	;;
	"bluetooth")
		bluetooth & exit 0
	 	;;
	"exit")
		exit 0
	 	;;
esac
