#!/usr/bin/bash
#taskbar script

TERM="scroll st"

choices=(
"htop"
"calcurse"
"pavucontrol"
"bluetooth"
"keymap-fix"
"exit"
)

while true; do
	sel=$(printf '%s\n' "${choices[@]}" | rofi -dmenu -p "taskbar: ")
	
	case $sel in
		"htop")
			$TERM "htop"
			exit 0
			;;
		"calcurse")
			$TERM "calcurse"
			exit 0
			;;
		"pavucontrol")
			pavucontrol & exit 0
		 	;;
		"bluetooth")
			bluetooth
			if [[ $? -eq 0 ]]; then
				exit 0
			fi
		 	;;
		"keymap-fix")
			setxkbmap -layout us,ru -option grp:alt_shift_toggle
			exit 0
			;;
		"exit")
			exit 0
		 	;;
	esac

	if [[ -z $sel ]]; then
		exit 0
	fi
done
